### ISSUE TITLE
`https://php-decimal.io/` Website is Down!

### ISSUE THREAD

**Issue by TheDevick** [php-decimal/php-decimal.github.io#4]
Hey!
So, the [php-decimal.io](https://php-decimal.io/) website is down!

![image](https://github.com/php-decimal/php-decimal.github.io/assets/71853418/90771262-bee3-4064-93d4-0936511287fa)

> Note that the [php-decimal.github.io/](https://php-decimal.github.io/#introduction) website works fine!

**Comment by rtheunissen** [comment]
Domain renewable came up and I couldn't justify the cost when the pages URL works just fine. It's probably doing though for existing links and bookmarks, so I'll fix that and while I'm at it see why the sandbox is broken.
